apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-repo
  annotations:
    nephio.org/requires-git-provider: Yes
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: repository
    repo: catalog-distros-sandbox
    workspaceName: main
  downstream:
    package: example-repo
    repo: mgmt
  injectors:
  - kind: WorkloadCluster
    name: example
  - group: ""
    version: v1
    kind: ConfigMap
    name: git-context
  pipeline:
    mutators:
    - image: ghcr.io/kptdev/krm-functions-catalog/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
        nephio.org/git-provider: example
        nephio.org/git-org: example
